export const testData = [
	{
		id: 0,
		name: 'fruits',
		words: [
			{ id: 0, word: 'apple', translation: 'obuolys' },
			{ id: 1, word: 'banana', translation: 'bananas' },
			{ id: 2, word: 'orange', translation: 'apelsinas' },
			{ id: 3, word: 'lemon', translation: 'citrina' },
		],
	},
	{
		id: 1,
		name: 'vegetables',
		words: [
			{ id: 0, word: 'potato', translation: 'bulvė' },
			{ id: 1, word: 'tomato', translation: 'pomidoras' },
			{ id: 2, word: 'cucumber', translation: 'agurkas' },
			{ id: 3, word: 'carrot', translation: 'morka' },
		],
	},
]

export const data = [
	{
		id: 0,
		name: 'adjectives',
		words: [
			{ id: 0, word: 'Good', translation: 'Geras' },
			{ id: 1, word: 'New', translation: 'Naujas' },
			{ id: 2, word: 'First', translation: 'Pirmas' },
			{ id: 3, word: 'Last', translation: 'Paskutinis' },
			{ id: 4, word: 'Long', translation: 'Ilgas' },
			{ id: 5, word: 'Great', translation: 'Puikus' },
			{ id: 6, word: 'Little', translation: 'Mažas' },
			{ id: 7, word: 'Own', translation: 'Savo' },
			{ id: 8, word: 'Other', translation: 'Kitas' },
			{ id: 9, word: 'Old', translation: 'Senas' },
			{ id: 10, word: 'Right', translation: 'Teisingas' },
			{ id: 11, word: 'Big', translation: 'Didelis' },
			{ id: 12, word: 'High', translation: 'Aukštas' },
			{ id: 13, word: 'Different', translation: 'Skirtingas' },
			{ id: 14, word: 'Small', translation: 'Mažas' },
			{ id: 15, word: 'Large', translation: 'Didelis' },
			{ id: 16, word: 'Next', translation: 'Kitas' },
			{ id: 17, word: 'Early', translation: 'Ankstus' },
			{ id: 18, word: 'Young', translation: 'Jaunas' },
			{ id: 19, word: 'Important', translation: 'Svarbus' },
			{ id: 20, word: 'Few', translation: 'Kelios' },
			{ id: 21, word: 'Public', translation: 'Viešas' },
			{ id: 22, word: 'Bad', translation: 'Blogas' },
			{ id: 23, word: 'Same', translation: 'Tas pats' },
			{ id: 24, word: 'Able', translation: 'Galintis' },
			{ id: 25, word: 'Open', translation: 'Atviras' },
			{ id: 26, word: 'Last', translation: 'Paskutinis' },
			{ id: 27, word: 'Short', translation: 'Trumpas' },
			{ id: 28, word: 'Early', translation: 'Ankstus' },
			{ id: 29, word: 'Best', translation: 'Geriausias' },
			{ id: 30, word: 'Strong', translation: 'Stiprus' },
			{ id: 31, word: 'Easy', translation: 'Lengvas' },
			{ id: 32, word: 'Free', translation: 'Nemokamas' },
			{ id: 33, word: 'Clear', translation: 'Aiškus' },
			{ id: 34, word: 'Hard', translation: 'Sunkus' },
			{ id: 35, word: 'Full', translation: 'Pilnas' },
			{ id: 36, word: 'Whole', translation: 'Visas' },
			{ id: 37, word: 'True', translation: 'Tikras' },
			{ id: 38, word: 'Safe', translation: 'Saugus' },
			{ id: 39, word: 'Special', translation: 'Specialus' },
			{ id: 40, word: 'Happy', translation: 'Laimingas' },
			{ id: 41, word: 'Certain', translation: 'Tikras' },
			{ id: 42, word: 'Red', translation: 'Raudonas' },
			{ id: 43, word: 'Blue', translation: 'Mėlynas' },
			{ id: 44, word: 'Black', translation: 'Juodas' },
			{ id: 45, word: 'White', translation: 'Balto' },
			{ id: 46, word: 'Green', translation: 'Žalias' },
			{ id: 47, word: 'Yellow', translation: 'Geltonas' },
			{ id: 48, word: 'Brown', translation: 'Rudas' },
			{ id: 49, word: 'Pink', translation: 'Rožinis' },
		],
	},
]
