export const testData = [
	{
		id: 0,
		name: 'fruits',
		words: [
			{ id: 0, word: 'apple', translation: 'obuolys' },
			{ id: 1, word: 'banana', translation: 'bananas' },
			{ id: 2, word: 'orange', translation: 'apelsinas' },
			{ id: 3, word: 'lemon', translation: 'citrina' },
		],
	},
	{
		id: 1,
		name: 'vegetables',
		words: [
			{ id: 0, word: 'potato', translation: 'bulvė' },
			{ id: 1, word: 'tomato', translation: 'pomidoras' },
			{ id: 2, word: 'cucumber', translation: 'agurkas' },
			{ id: 3, word: 'carrot', translation: 'morka' },
		],
	},
]

export const data = [
	{
		id: 0,
		name: 'adjectives (būdvardžiai)',
		words: [
			{ id: 0, word: 'Good', translation: 'Geras' },
			{ id: 1, word: 'New', translation: 'Naujas' },
			{ id: 2, word: 'First', translation: 'Pirmas' },
			{ id: 3, word: 'Last', translation: 'Paskutinis' },
			{ id: 4, word: 'Long', translation: 'Ilgas' },
			{ id: 5, word: 'Great', translation: 'Puikus' },
			{ id: 6, word: 'Little', translation: 'Mažas' },
			{ id: 7, word: 'Own', translation: 'Savo' },
			{ id: 8, word: 'Other', translation: 'Kitas' },
			{ id: 9, word: 'Old', translation: 'Senas' },
			{ id: 10, word: 'Right', translation: 'Teisingas' },
			{ id: 11, word: 'Big', translation: 'Didelis' },
			{ id: 12, word: 'High', translation: 'Aukštas' },
			{ id: 13, word: 'Different', translation: 'Skirtingas' },
			{ id: 14, word: 'Small', translation: 'Mažas' },
			{ id: 15, word: 'Large', translation: 'Didelis' },
			{ id: 16, word: 'Next', translation: 'Kitas' },
			{ id: 17, word: 'Early', translation: 'Ankstus' },
			{ id: 18, word: 'Young', translation: 'Jaunas' },
			{ id: 19, word: 'Important', translation: 'Svarbus' },
			{ id: 20, word: 'Few', translation: 'Kelios' },
			{ id: 21, word: 'Public', translation: 'Viešas' },
			{ id: 22, word: 'Bad', translation: 'Blogas' },
			{ id: 23, word: 'Same', translation: 'Tas pats' },
			{ id: 24, word: 'Able', translation: 'Galintis' },
			{ id: 25, word: 'Open', translation: 'Atviras' },
			{ id: 26, word: 'Last', translation: 'Paskutinis' },
			{ id: 27, word: 'Short', translation: 'Trumpas' },
			{ id: 28, word: 'Early', translation: 'Ankstus' },
			{ id: 29, word: 'Best', translation: 'Geriausias' },
			{ id: 30, word: 'Strong', translation: 'Stiprus' },
			{ id: 31, word: 'Easy', translation: 'Lengvas' },
			{ id: 32, word: 'Free', translation: 'Nemokamas' },
			{ id: 33, word: 'Clear', translation: 'Aiškus' },
			{ id: 34, word: 'Hard', translation: 'Sunkus' },
			{ id: 35, word: 'Full', translation: 'Pilnas' },
			{ id: 36, word: 'Whole', translation: 'Visas' },
			{ id: 37, word: 'True', translation: 'Tikras' },
			{ id: 38, word: 'Safe', translation: 'Saugus' },
			{ id: 39, word: 'Special', translation: 'Specialus' },
			{ id: 40, word: 'Happy', translation: 'Laimingas' },
			{ id: 41, word: 'Certain', translation: 'Tikras' },
			{ id: 42, word: 'Red', translation: 'Raudonas' },
			{ id: 43, word: 'Blue', translation: 'Mėlynas' },
			{ id: 44, word: 'Black', translation: 'Juodas' },
			{ id: 45, word: 'White', translation: 'Balto' },
			{ id: 46, word: 'Green', translation: 'Žalias' },
			{ id: 47, word: 'Yellow', translation: 'Geltonas' },
			{ id: 48, word: 'Brown', translation: 'Rudas' },
			{ id: 49, word: 'Pink', translation: 'Rožinis' },
		],
	},

	{
		id: 1,
		name: 'pronouns (įvardžiai)',
		words: [
			{ id: 0, word: 'I', translation: 'Aš' },
			{ id: 1, word: 'You', translation: 'Tu, tave' },
			{ id: 2, word: 'He', translation: 'Jis' },
			{ id: 3, word: 'She', translation: 'Ji' },
			{ id: 4, word: 'It', translation: 'Tas (daiktas)' },
			{ id: 5, word: 'We', translation: 'Mes' },
			{ id: 6, word: 'They', translation: 'Jie' },
			{ id: 7, word: 'Me', translation: 'Mane' },
			{ id: 8, word: 'Him', translation: 'Jį' },
			{ id: 9, word: 'Her', translation: 'Ją' },
			{ id: 10, word: 'Us', translation: 'Mus' },
			{ id: 11, word: 'Them', translation: 'Juos/Jas' },
			{ id: 12, word: 'Myself', translation: 'Pats/Pati (sau)' },
			{ id: 13, word: 'Yourself', translation: 'Pats/Pati (sau, tu)' },
			{ id: 14, word: 'Himself', translation: 'Pats (sau, jis)' },
			{ id: 15, word: 'Herself', translation: 'Pats (sau, ji)' },
			{ id: 16, word: 'Itself', translation: 'Pats (sau, daiktas)' },
			{ id: 17, word: 'Ourselves', translation: 'Patys (sau, mes)' },
			{ id: 18, word: 'Yourselves', translation: 'Patys (sau, jūs)' },
			{ id: 19, word: 'Themselves', translation: 'Patys (sau, jie)' },
		],
	},

	{
		id: 2,
		name: 'nouns (daiktavardžiai)',
		words: [
			{ id: 0, word: 'Person', translation: 'Asmuo' },
			{ id: 1, word: 'Time', translation: 'Laikas' },
			{ id: 2, word: 'Year', translation: 'Metai' },
			{ id: 3, word: 'Day', translation: 'Diena' },
			{ id: 4, word: 'Man', translation: 'Vyras' },
			{ id: 5, word: 'Woman', translation: 'Moteris' },
			{ id: 6, word: 'Child', translation: 'Vaikas' },
			{ id: 7, word: 'Family', translation: 'Šeima' },
			{ id: 8, word: 'House', translation: 'Namai' },
			{ id: 9, word: 'Place', translation: 'Vieta' },
			{ id: 10, word: 'Work', translation: 'Darbas' },
			{ id: 11, word: 'Week', translation: 'Savaitė' },
			{ id: 12, word: 'Month', translation: 'Mėnuo' },
			{ id: 13, word: 'Name', translation: 'Vardas' },
			{ id: 14, word: 'Friend', translation: 'Draugas' },
			{ id: 15, word: 'Money', translation: 'Pinigai' },
			{ id: 16, word: 'Food', translation: 'Maistas' },
			{ id: 17, word: 'Water', translation: 'Vanduo' },
			{ id: 18, word: 'Book', translation: 'Knyga' },
			{ id: 19, word: 'School', translation: 'Mokykla' },
			{ id: 20, word: 'Job', translation: 'Darbas (užimtumas)' },
			{ id: 21, word: 'City', translation: 'Miestas' },
			{ id: 22, word: 'Country', translation: 'Šalis' },
			{ id: 23, word: 'Friendship', translation: 'Draugystė' },
			{ id: 24, word: 'Love', translation: 'Meilė' },
			{ id: 25, word: 'Language', translation: 'Kalba' },
			{ id: 26, word: 'Life', translation: 'Gyvenimas' },
			{ id: 27, word: 'Nature', translation: 'Gamta' },
			{ id: 28, word: 'Problem', translation: 'Problema' },
			{ id: 29, word: 'Question', translation: 'Klausimas' },
			{ id: 30, word: 'Thing', translation: 'Dalykas' },
		],
	},
	{
		id: 3,
		name: 'verbs (veiksmažodžiai)',
		words: [
			{ id: 0, word: 'Be', translation: 'Būti' },
			{ id: 1, word: 'Have', translation: 'Turėti' },
			{ id: 2, word: 'Do', translation: 'Daryti' },
			{ id: 3, word: 'Say', translation: 'Sakyti' },
			{ id: 4, word: 'Get', translation: 'Gauti' },
			{ id: 5, word: 'Make', translation: 'Gaminti' },
			{ id: 6, word: 'Go', translation: 'Eiti' },
			{ id: 7, word: 'Know', translation: 'Žinoti' },
			{ id: 8, word: 'Take', translation: 'Imti' },
			{ id: 9, word: 'See', translation: 'Matyti' },
			{ id: 10, word: 'Come', translation: 'Ateiti' },
			{ id: 11, word: 'Think', translation: 'Mąstyti' },
			{ id: 12, word: 'Look', translation: 'Žiūrėti' },
			{ id: 13, word: 'Want', translation: 'Norėti' },
			{ id: 14, word: 'Give', translation: 'Duoti' },
			{ id: 15, word: 'Use', translation: 'Naudoti' },
			{ id: 16, word: 'Find', translation: 'Rasti' },
			{ id: 17, word: 'Tell', translation: 'Pasakyti' },
			{ id: 18, word: 'Ask', translation: 'Klausti' },
			{ id: 19, word: 'Work', translation: 'Dirbti' },
			{ id: 20, word: 'Seem', translation: 'Atrodyti' },
			{ id: 21, word: 'Feel', translation: 'Jausti' },
			{ id: 22, word: 'Try', translation: 'Bandyti' },
			{ id: 23, word: 'Leave', translation: 'Išeiti' },
			{ id: 24, word: 'Call', translation: 'Skambinti' },
			{ id: 25, word: 'Need', translation: 'Reikėti' },
			{ id: 26, word: 'Want', translation: 'Norėti' },
			{ id: 27, word: 'Become', translation: 'Tapti' },
			{ id: 28, word: 'Leave', translation: 'Palikti' },
			{ id: 29, word: 'Put', translation: 'Padėti' },
			{ id: 30, word: 'Mean', translation: 'Reikšti' },
		],
	},

	{
		id: 4,
		name: 'sentences (sakiniai)',
		words: [
			{ id: 0, word: 'I have a book.', translation: 'Aš turiu knygą.' },
			{
				id: 1,
				word: 'She knows English.',
				translation: 'Ji žino anglų kalbą.',
			},
			{ id: 2, word: 'We are friends.', translation: 'Mes esame draugai.' },
			{ id: 3, word: 'He works in a city.', translation: 'Jis dirba mieste.' },
			{
				id: 4,
				word: 'The child is happy.',
				translation: 'Vaikas yra laimingas.',
			},
			{ id: 5, word: 'They want to go.', translation: 'Jie nori eiti.' },
			{ id: 6, word: 'She sees the sun.', translation: 'Ji mato saulę.' },
			{ id: 7, word: 'You are in school.', translation: 'Tu esi mokykloje.' },
			{ id: 8, word: 'I love nature.', translation: 'Aš myliu gamtą.' },
			{ id: 9, word: 'He has a problem.', translation: 'Jis turi problemą.' },
		],
	},
]
